version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    depends_on:
      - app
