version: '3.8'

services:
  app:
    image: descent1511/frontend:latest
    container_name: vue-app
    environment :
        VUE_APP_API_URL: http://192.168.0.102:8000

    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    depends_on:
      - app
