apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-chart.fullname" . }}
  labels:
    {{- include "web-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}

  selector:
    {{- include "web-chart.selectorLabels" . | nindent 4 }}
